import { Navigate, Route, Routes } from 'react-router-dom'
import { Layout } from './components/Layout'
import { Dashboard } from './pages/Dashboard'
import { FeaturePage } from './pages/DetailPages'
import { ApiProductDetails } from './pages/ApiProductDetails'
import { Passports } from './pages/Passports'
import { PcfPage } from './pages/PcfPage'
import { DigitalProductPassport } from './pages/DigitalProductPassport'
import { AuthPage } from './pages/AuthPage'
import { Operations } from './pages/Operations'
import { EconomicOperatorsPage } from './pages/EconomicOperatorsPage'
import { TenantManagementPage } from './pages/TenantManagementPage'
import { AssessmentPage } from './pages/AssessmentPage'
import { IdasAssessmentPage } from './pages/IdasAssessmentPage'
import { CatenaXPage, RegistryPage, ReportsPage } from './pages/PlatformCapabilities'
import { TenantAccessManagement } from './pages/TenantAccessManagement'
import { SelfOnboardingPage } from './pages/SelfOnboardingPage'
import { CreateDppPage } from './pages/CreateDppPage'
import { HelpPage } from './pages/HelpPage'
import { FileCheck2, ClipboardCheck } from 'lucide-react'

export default function App() { return <Routes><Route path="/login" element={<AuthPage />} /><Route path="/register" element={<SelfOnboardingPage />} /><Route element={<Layout />}><Route path="/" element={<Dashboard />} /><Route path="/tenants" element={<TenantManagementPage />} /><Route path="/companies" element={<EconomicOperatorsPage />} /><Route path="/products" element={<Operations type="products" />} /><Route path="/products/new" element={<CreateDppPage />} /><Route path="/products/:id" element={<ApiProductDetails />} /><Route path="/products/:id/passport" element={<DigitalProductPassport />} /><Route path="/materials" element={<Operations type="materials" />} /><Route path="/suppliers" element={<Operations type="suppliers" />} /><Route path="/compliance" element={<Operations type="compliance" />} /><Route path="/pcf" element={<PcfPage />} /><Route path="/passports" element={<Passports />} /><Route path="/assessment" element={<AssessmentPage />} /><Route path="/assessment/idas" element={<IdasAssessmentPage />} /><Route path="/reports" element={<ReportsPage />} /><Route path="/settings" element={<TenantAccessManagement />} /><Route path="/integrations/catena-x" element={<CatenaXPage />} /><Route path="/registry" element={<RegistryPage />} /><Route path="/help" element={<HelpPage />} /><Route path="*" element={<Navigate to="/" replace />} /></Route></Routes> }
